-- Offline sanity check for the Hyprland Lua config.
--
--   lua tests/check.lua
--
-- Hyprland is not needed. This builds a stub `hl` global that mirrors the
-- documented API, executes the config against it, and fails on anything the
-- real compositor would reject: syntax errors, unknown `hl.*` functions,
-- unknown dispatchers, unknown config sections. It cannot validate individual
-- option values — only that the config loads and calls things that exist.

local ROOT = (arg[0]:match("(.*)/tests/check%.lua$")) or "."
local CONFIG = ROOT .. "/config/hypr"

local calls = { binds = 0, rules = 0, env = 0, monitors = 0, submaps = 0, autostart = 0 }
local errors = {}

local function fail(msg)
    errors[#errors + 1] = msg
end

-- A table whose unknown keys are an error, so typos surface instead of
-- silently returning nil.
local function strict(name, fields)
    return setmetatable({}, {
        __index = function(_, key)
            local v = fields[key]
            if v == nil then
                fail(("unknown member %s.%s"):format(name, tostring(key)))
                return function() end
            end
            return v
        end,
    })
end

local function recorder() return function() return {} end end

local function group(name, names)
    local fields = {}
    for _, n in ipairs(names) do fields[n] = recorder() end
    return strict(name, fields)
end

-- Dispatchers, per https://wiki.hypr.land/Configuring/Basics/Dispatchers/
local dsp_general = {
    "exec_cmd", "exec_raw", "focus", "exit", "submap", "pass", "send_shortcut",
    "send_key_state", "layout", "dpms", "event", "global", "force_idle",
    "no_op", "force_renderer_reload", "release_input_capture",
}
local dsp_window = {
    "close", "kill", "signal", "float", "fullscreen", "fullscreen_state",
    "pseudo", "move", "swap", "center", "cycle_next", "tag", "clear_tags",
    "toggle_swallow", "pin", "alter_zorder", "set_prop", "deny_from_group",
    "drag", "resize",
}
local dsp_workspace = { "rename", "change_id", "move", "swap_monitors", "toggle_special" }
local dsp_group     = { "toggle", "next", "prev", "active", "move_window", "lock", "lock_active" }
local dsp_cursor    = { "move_to_corner", "move" }

local dsp_fields = {}
for _, n in ipairs(dsp_general) do dsp_fields[n] = recorder() end
dsp_fields.window    = group("hl.dsp.window", dsp_window)
dsp_fields.workspace = group("hl.dsp.workspace", dsp_workspace)
dsp_fields.group     = group("hl.dsp.group", dsp_group)
dsp_fields.cursor    = group("hl.dsp.cursor", dsp_cursor)

-- Top-level config sections, per Configuring/Basics/Variables.
local SECTIONS = {
    general = true, decoration = true, animations = true, input = true,
    gestures = true, group = true, misc = true, binds = true, xwayland = true,
    opengl = true, render = true, cursor = true, ecosystem = true,
    quirks = true, debug = true, experimental = true, dwindle = true,
    master = true, scrolling = true, monocle = true, autogenerated = true,
    input_capture = true,
}

local start_handlers = {}

local hl_fields = {
    dsp = strict("hl.dsp", dsp_fields),

    config = function(t)
        for section in pairs(t) do
            if not SECTIONS[section] then
                fail("unknown config section: " .. tostring(section))
            end
        end
    end,

    bind = function(keys, dispatcher, flags)
        calls.binds = calls.binds + 1
        if type(keys) ~= "string" then fail("hl.bind: keys must be a string") end
        local t = type(dispatcher)
        if t ~= "table" and t ~= "function" then
            fail("hl.bind(" .. tostring(keys) .. "): dispatcher must be a table or function, got " .. t)
        end
        if flags ~= nil and type(flags) ~= "table" then
            fail("hl.bind(" .. tostring(keys) .. "): flags must be a table")
        end
        return { set_enabled = function() end }
    end,

    define_submap = function(name, body)
        calls.submaps = calls.submaps + 1
        if type(body) ~= "function" then fail("hl.define_submap: body must be a function") end
        body()
    end,

    on = function(event, fn)
        if type(fn) ~= "function" then fail("hl.on: handler must be a function") end
        if event == "hyprland.start" then start_handlers[#start_handlers + 1] = fn end
    end,

    env = function() calls.env = calls.env + 1 end,
    monitor = function() calls.monitors = calls.monitors + 1 end,

    window_rule = function(r)
        calls.rules = calls.rules + 1
        if type(r) ~= "table" or type(r.match) ~= "table" then
            fail("hl.window_rule: needs a `match` table")
        end
        return { set_enabled = function() end }
    end,

    layer_rule = function(r)
        calls.rules = calls.rules + 1
        if type(r) ~= "table" or type(r.match) ~= "table" then
            fail("hl.layer_rule: needs a `match` table")
        end
        return { set_enabled = function() end }
    end,

    workspace_rule = recorder(),
    gesture        = recorder(),
    device         = recorder(),
    curve          = recorder(),
    animation      = recorder(),
    permission     = recorder(),
    dispatch       = recorder(),
    timer          = recorder(),
    exec_cmd       = function() calls.autostart = calls.autostart + 1 end,
    exec_raw       = function() calls.autostart = calls.autostart + 1 end,
    notify         = recorder(),
}

hl = strict("hl", hl_fields)

package.path = CONFIG .. "/?.lua;" .. package.path

local ok, err = pcall(dofile, CONFIG .. "/hyprland.lua")
if not ok then
    io.stderr:write("FAIL: config raised an error\n  " .. tostring(err) .. "\n")
    os.exit(1)
end

-- Autostart bodies only run on the hyprland.start event; run them too.
for _, fn in ipairs(start_handlers) do
    local ok2, err2 = pcall(fn)
    if not ok2 then fail("hyprland.start handler failed: " .. tostring(err2)) end
end

if #errors > 0 then
    io.stderr:write("FAIL: " .. #errors .. " problem(s)\n")
    for _, e in ipairs(errors) do io.stderr:write("  - " .. e .. "\n") end
    os.exit(1)
end

print(("OK: %d binds, %d rules, %d env vars, %d monitor rules, %d submaps, %d autostart commands")
    :format(calls.binds, calls.rules, calls.env, calls.monitors, calls.submaps, calls.autostart))
