-- Offline sanity check for the Hyprland Lua config.
--
--   lua tests/check.lua
--
-- Hyprland is not needed. This builds a stub `hl` global that mirrors the
-- documented API, executes the config against it, and fails on anything the
-- real compositor would reject: syntax errors, unknown `hl.*` functions,
-- unknown dispatchers, unknown config sections. It cannot validate individual
-- option values — only that the config loads and calls things that exist.

local ROOT = (arg[0]:match("(.*)/tests/check%.lua$")) or "."
local CONFIG = ROOT .. "/config/hypr"

local calls = { binds = 0, rules = 0, env = 0, monitors = 0, submaps = 0, autostart = 0 }
local errors = {}

local function fail(msg)
    errors[#errors + 1] = msg
end

-- A table whose unknown keys are an error, so typos surface instead of
-- silently returning nil.
local function strict(name, fields)
    return setmetatable({}, {
        __index = function(_, key)
            local v = fields[key]
            if v == nil then
                fail(("unknown member %s.%s"):format(name, tostring(key)))
                return function() end
            end
            return v
        end,
    })
end

local function recorder() return function() return {} end end

-- Every shell command the config runs, collected for the package check below.
local commands = {}
local function record_cmd(cmd)
    if type(cmd) == "string" then commands[#commands + 1] = cmd end
end

local function group(name, names)
    local fields = {}
    for _, n in ipairs(names) do fields[n] = recorder() end
    return strict(name, fields)
end

-- Dispatchers, per https://wiki.hypr.land/Configuring/Basics/Dispatchers/
local dsp_general = {
    "exec_cmd", "exec_raw", "focus", "exit", "submap", "pass", "send_shortcut",
    "send_key_state", "layout", "dpms", "event", "global", "force_idle",
    "no_op", "force_renderer_reload", "release_input_capture",
}
local dsp_window = {
    "close", "kill", "signal", "float", "fullscreen", "fullscreen_state",
    "pseudo", "move", "swap", "center", "cycle_next", "tag", "clear_tags",
    "toggle_swallow", "pin", "alter_zorder", "set_prop", "deny_from_group",
    "drag", "resize",
}
local dsp_workspace = { "rename", "change_id", "move", "swap_monitors", "toggle_special" }
local dsp_group     = { "toggle", "next", "prev", "active", "move_window", "lock", "lock_active" }
local dsp_cursor    = { "move_to_corner", "move" }

local dsp_fields = {}
for _, n in ipairs(dsp_general) do dsp_fields[n] = recorder() end
dsp_fields.exec_cmd = function(cmd) record_cmd(cmd) return {} end
dsp_fields.exec_raw = function(cmd) record_cmd(cmd) return {} end
dsp_fields.window    = group("hl.dsp.window", dsp_window)
dsp_fields.workspace = group("hl.dsp.workspace", dsp_workspace)
dsp_fields.group     = group("hl.dsp.group", dsp_group)
dsp_fields.cursor    = group("hl.dsp.cursor", dsp_cursor)

-- Top-level config sections, per Configuring/Basics/Variables.
local SECTIONS = {
    general = true, decoration = true, animations = true, input = true,
    gestures = true, group = true, misc = true, binds = true, xwayland = true,
    opengl = true, render = true, cursor = true, ecosystem = true,
    quirks = true, debug = true, experimental = true, dwindle = true,
    master = true, scrolling = true, monocle = true, autogenerated = true,
    input_capture = true,
}

local start_handlers = {}

-- Bind normalisation, so SUPER+L and SUPER+l are recognised as the same key.
-- Hyprland matches keys case-insensitively; two binds on one combination means
-- the later one silently wins and the earlier one is dead.
local MODIFIERS = {
    SUPER = true, SHIFT = true, ALT = true, CTRL = true, CONTROL = true,
    MOD = true, META = true,
}

local bindings = {}      -- normalised bind -> where it was first seen
local current_scope = "global"

local function normalise_bind(keys)
    local mods, key = {}, nil
    for part in keys:gmatch("[^+]+") do
        part = part:gsub("^%s*(.-)%s*$", "%1"):upper()
        if MODIFIERS[part] then
            mods[#mods + 1] = part
        else
            key = part
        end
    end
    table.sort(mods)
    return table.concat(mods, "+") .. (key and ("+" .. key) or "")
end

local hl_fields = {
    dsp = strict("hl.dsp", dsp_fields),

    config = function(t)
        for section in pairs(t) do
            if not SECTIONS[section] then
                fail("unknown config section: " .. tostring(section))
            end
        end
    end,

    bind = function(keys, dispatcher, flags)
        calls.binds = calls.binds + 1

        if type(keys) == "string" then
            local id = current_scope .. " :: " .. normalise_bind(keys)
            if bindings[id] then
                fail(("%s and %s are the same combination — one of them is dead")
                    :format(bindings[id], keys))
            else
                bindings[id] = keys
            end
        end
        if type(keys) ~= "string" then fail("hl.bind: keys must be a string") end
        local t = type(dispatcher)
        if t ~= "table" and t ~= "function" then
            fail("hl.bind(" .. tostring(keys) .. "): dispatcher must be a table or function, got " .. t)
        end
        if flags ~= nil and type(flags) ~= "table" then
            fail("hl.bind(" .. tostring(keys) .. "): flags must be a table")
        end
        return { set_enabled = function() end }
    end,

    define_submap = function(name, body)
        calls.submaps = calls.submaps + 1
        if type(body) ~= "function" then fail("hl.define_submap: body must be a function") end
        -- Binds inside a submap live in their own namespace.
        local outer = current_scope
        current_scope = "submap " .. tostring(name)
        body()
        current_scope = outer
    end,

    on = function(event, fn)
        if type(fn) ~= "function" then fail("hl.on: handler must be a function") end
        if event == "hyprland.start" then start_handlers[#start_handlers + 1] = fn end
    end,

    env = function() calls.env = calls.env + 1 end,
    monitor = function() calls.monitors = calls.monitors + 1 end,

    window_rule = function(r)
        calls.rules = calls.rules + 1
        if type(r) ~= "table" or type(r.match) ~= "table" then
            fail("hl.window_rule: needs a `match` table")
        end
        return { set_enabled = function() end }
    end,

    layer_rule = function(r)
        calls.rules = calls.rules + 1
        if type(r) ~= "table" or type(r.match) ~= "table" then
            fail("hl.layer_rule: needs a `match` table")
        end
        return { set_enabled = function() end }
    end,

    workspace_rule = recorder(),
    gesture        = recorder(),
    device         = recorder(),
    curve          = recorder(),
    animation      = recorder(),
    permission     = recorder(),
    dispatch       = recorder(),
    timer          = recorder(),
    exec_cmd       = function(cmd) calls.autostart = calls.autostart + 1 record_cmd(cmd) end,
    exec_raw       = function(cmd) calls.autostart = calls.autostart + 1 record_cmd(cmd) end,
    notify         = recorder(),
}

hl = strict("hl", hl_fields)

package.path = CONFIG .. "/?.lua;" .. package.path

local ok, err = pcall(dofile, CONFIG .. "/hyprland.lua")
if not ok then
    io.stderr:write("FAIL: config raised an error\n  " .. tostring(err) .. "\n")
    os.exit(1)
end

-- Autostart bodies only run on the hyprland.start event; run them too.
for _, fn in ipairs(start_handlers) do
    local ok2, err2 = pcall(fn)
    if not ok2 then fail("hyprland.start handler failed: " .. tostring(err2)) end
end

-- ---------------------------------------------------------------------------
-- Every program the config invokes must be covered by a package list.
-- This is what catches a keybind calling something nobody installs.

local PACKAGE_OF = {
    kitty        = "kitty",
    wofi         = "wofi",
    waybar       = "waybar",
    mako         = "mako",
    makoctl      = "mako",
    wpctl        = "wireplumber",
    hyprctl      = "hyprland",
    hyprshutdown = "hyprland",
    hyprlauncher = "hyprlauncher",
    hyprpaper    = "hyprpaper",
    btop         = "btop",
    ["nvidia-smi"] = "nvidia-utils",
    playerctl     = "playerctl",
    pavucontrol   = "pavucontrol",
    udiskie       = "udiskie",
    grim          = "grim",
    slurp         = "slurp",
    cliphist      = "cliphist",
    hyprlock     = "hyprlock",
    hypridle     = "hypridle",
    grim         = "grim",
    slurp        = "slurp",
    cliphist     = "cliphist",
    jq           = "jq",
    ["notify-send"]          = "libnotify",
    ["wl-copy"]              = "wl-clipboard",
    ["wl-paste"]             = "wl-clipboard",
    ["blueman-applet"]       = "blueman",
    ["blueman-manager"]      = "blueman",
    ["nm-applet"]            = "network-manager-applet",
    ["nm-connection-editor"] = "network-manager-applet",
}

-- Shell builtins and things the base system always provides.
local ALWAYS_PRESENT = {
    ["command"] = true, ["sh"] = true, ["systemctl"] = true, ["pkill"] = true,
    ["echo"] = true, ["true"] = true, ["false"] = true, ["test"] = true,
    -- systemd and glib are part of any Arch install with a desktop on it
    ["loginctl"] = true, ["gsettings"] = true,
}

-- A command starting with ~/ or / is one of our own scripts rather than a
-- package. Those have to exist in the repo, and be executable.
local seen_scripts = {}
local function check_script(path)
    local relative = path:match("^~/%.config/(.+)$")
    if not relative then return false end
    if seen_scripts[relative] then return true end
    seen_scripts[relative] = true

    local file = ROOT .. "/config/" .. relative
    local f = io.open(file, "r")
    if not f then
        fail(("config runs '%s', but %s does not exist in the repo")
            :format(path, "config/" .. relative))
        return true
    end
    f:close()

    -- io cannot stat, so ask the shell whether the bit is set.
    local p = io.popen('test -x "' .. file .. '" && echo yes')
    local executable = p and p:read("l") == "yes"
    if p then p:close() end
    if not executable then
        fail(("%s is not executable — chmod +x it"):format("config/" .. relative))
    end
    return true
end

-- Waybar runs commands too, and they live in JSON rather than Lua. Some
-- modules take an action name there instead of a program; those are not
-- commands and must not be looked up as packages.
local WAYBAR_ACTIONS = { activate = true, toggle = true, close = true }

do
    local f = io.open(ROOT .. "/config/waybar/config.jsonc", "r")
    if f then
        local text = f:read("a")
        for cmd in text:gmatch('"on%-click[%w%-]*"%s*:%s*"([^"]+)"') do
            if not WAYBAR_ACTIONS[cmd] then record_cmd(cmd) end
        end
        for cmd in text:gmatch('"exec"%s*:%s*"([^"]+)"') do
            record_cmd(cmd)
        end
        f:close()
    end
end

-- Union of every packages/*.txt, with comments stripped.
local listed = {}
local have_lists = false
local ls = io.popen('ls "' .. ROOT .. '/packages" 2>/dev/null')
if ls then
    for name in ls:lines() do
        local f = io.open(ROOT .. "/packages/" .. name, "r")
        if f then
            have_lists = true
            for line in f:lines() do
                local pkg = line:gsub("#.*", ""):gsub("%s", "")
                if pkg ~= "" then listed[pkg] = true end
            end
            f:close()
        end
    end
    ls:close()
end

if have_lists then
    local seen = {}
    for _, cmd in ipairs(commands) do
        -- Drop redirections, then treat |, & and ; as command boundaries.
        local stripped = cmd:gsub("%d*[<>]+%s*%S+", " ")
        for segment in stripped:gsub("[|&;]+", "\n"):gmatch("[^\n]+") do
            local script = segment:match("^%s*([~/][%w%._%-/]*)")
            if script and check_script(script) then goto continue end

            local found = { segment:match("^%s*([%w%._%-/]+)") }
            -- A terminal launcher hides a second program behind -e.
            local nested = segment:match("%-e%s+([%w%._%-/]+)")
            if nested then found[#found + 1] = nested end

            for _, binary in ipairs(found) do
                binary = binary:match("([^/]+)$")
                if binary and not ALWAYS_PRESENT[binary] and not seen[binary] then
                    seen[binary] = true
                    local pkg = PACKAGE_OF[binary]
                    if not pkg then
                        fail(("config runs '%s', which the package map in this test does not know")
                            :format(binary))
                    elseif not listed[pkg] then
                        fail(("config runs '%s', but package '%s' is in no packages/*.txt")
                            :format(binary, pkg))
                    end
                end
            end
            ::continue::
        end
    end
end

if #errors > 0 then
    io.stderr:write("FAIL: " .. #errors .. " problem(s)\n")
    for _, e in ipairs(errors) do io.stderr:write("  - " .. e .. "\n") end
    os.exit(1)
end

print(("OK: %d binds, %d rules, %d env vars, %d monitor rules, %d submaps, %d autostart commands")
    :format(calls.binds, calls.rules, calls.env, calls.monitors, calls.submaps, calls.autostart))
print(("OK: %d shell commands, every program covered by a package list"):format(#commands))
